### ISSUE TITLE
Request to have possibility to update management console context path

### ISSUE THREAD

**Issue by sweeguan-ng** [arkmq-org/activemq-artemis-broker-kubernetes-image#26]
**Is your feature request related to a problem? Please describe.**
Currently the management console context path is hardcoded to /console, i can't really see way to update it besides manually change it in bootstrap.xml

**Describe the solution you'd like**
Additional parameter to update management console URL as part of image.yaml, can be something like AMQ_CONSOLE_CONTEXT, will be even better to have artemis-plugin, and activemq-branding to be customizable context path.

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by gaohoward** [comment]
@sweeguan-ng hey you can use init container to modify the bootstrap.xml and other configs needed.

**Comment by gaohoward** [comment]
of course you need to use operator. :)

**Comment by sweeguan-ng** [comment]
hi @gaohoward appreciate that, thanks :)
