### ISSUE TITLE
Update drain.sh in activemq-artemis-launch module to use python3

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/activemq-artemis-broker-kubernetes-image#51]
**Is your feature request related to a problem? Please describe.**
Right now the script is using python2 which is very old.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by tlbueno** [comment]
fixed by https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/pull/82
