### ISSUE TITLE
drain.sh scaledown should wait for broker to stop and verify messageCount==0 before exit success

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/activemq-artemis-broker-kubernetes-image#52]
**Describe the bug**
The drain.sh in amq-launch-module should wait for the broker (which is running background) to finish
before exit. This is useful for broker to shutdown properly and for checking out broker status when scale
down fails.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - CEKit version [e.g. 3.5.0]
 - Container build tool [e.g. podman]

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by gtully** [comment]
more than this, it cannot depend on the status code from the scale request b/c errors are just logged and status is ok.

We need to have a verification stage at the end.
wait for stopped
start, verify  messagesCount = 0  on all queues with queue stat, stop
return messageCount == 0

We can only reclaim the PVC when we know there are no pending messages.

**Comment by gtully** [comment]
see logs in https://github.com/artemiscloud/activemq-artemis-operator/issues/663 for some more detail on failures reported in the logs but not in the http status return code.
Best if we verify via messageCount==0, or the relevant per queue metric
