### ISSUE TITLE
Delaying pod exit in case of scaledown failure to assist debug 

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/activemq-artemis-broker-kubernetes-image#54]
**Describe the bug**
When scaledown returns failure the drain pod will be restarted repeatedly by kubernetes
if we can add some time delay to let the failing pod to live for sometime before restart
we can give the user a chance to login to the pod and inspect the logs etc to find out
clue about why it's failing.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - CEKit version [e.g. 3.5.0]
 - Container build tool [e.g. podman]

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by tlbueno** [comment]
@gaohoward I think this is already implemented right? I can see this line in the drainer script: https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/blob/89a5d7600961569c4e3eef0541d977e57d6d5777/modules/activemq-artemis-launch/added/drain.sh#L161

If so, we can get this one closed.

**Comment by tlbueno** [comment]
After discussing it with @gaohoward we agreed that it can be closed.
