### ISSUE TITLE
screenshots i know how to do that.

### ISSUE THREAD

**Issue by cliffy93** [arkmq-org/activemq-artemis-broker-kubernetes-image#60]
**Describe the bug**

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - CEKit version [e.g. 3.5.0]
 - Container build tool [e.g. podman]

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
@cliffy93 I'm closing this issue because it does't include enough details. Feel free to add the requeired details and reopen it.
