### ISSUE TITLE
The container image for arm64 doesn't include the aarch_64 netty-tcnative artifact

### ISSUE THREAD

**Issue by brusdev** [arkmq-org/activemq-artemis-broker-kubernetes-image#70]
The container image quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.19 for the arm64 doesn't include the aarch_64 netty-tcnative artifact.

**Comment by tlbueno** [comment]
Closing this as it was fixed by https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/commit/70f5a197b464fbc36b380b1fdf555dc6c09a71bc
