### ISSUE TITLE
Message group rebalancing not working when new clients connect

### ISSUE THREAD

**Issue by mm-mse** [arkmq-org/activemq-artemis-broker-kubernetes-image#99]
**Describe the bug**
When a queue contains already messages that are part of a message group then only the first consumer will be assigned to all these message groups. ActiveMQ message groups are not rebalanced when new consumers are added to the broker. Even though `group-rebalance=true` or `resetAllGroups` is invoked via the management API. Only new message groups get assigned to newer clients.

**To Reproduce**
1. Get 2.31.2 of the Artemis Broker
2. Create queue with group-rebalance=true
3. Create messages with message groups
4. Start clients one by one as pods

**Platform (please complete the following information):**
 - OS: Kubernetes
 - Version: v1.24.17

**Expected behavior**
The newer clients should also receive Messages with GroupIDs that were already in the queue before they were connected to the broker.

**Additional context**
 Running on Kubernetes with an operator
Messages are created on the web console
Message groups are set at creation of messages via the Header "_AMQ_GROUP_ID"
[Artemis documentation about message groups](https://activemq.apache.org/components/artemis/documentation/latest/message-grouping.html)

**Comment by brusdev** [comment]
This issue is related to Apache ActiveMQ Artemis, see https://activemq.apache.org/contact
